// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkuIzBF5bUAs8-jIn6oRfrBCyqyQWooM',
    appId: '1:408373931839:web:c393958984c88e47a4ed8a',
    messagingSenderId: '408373931839',
    projectId: 'radio-9ec61',
    authDomain: 'radio-9ec61.firebaseapp.com',
    databaseURL: 'https://radio-9ec61-default-rtdb.firebaseio.com',
    storageBucket: 'radio-9ec61.appspot.com',
    measurementId: 'G-HJ34JX03ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJtrLnr-yL-pvzeJOY2AK5nHOG0XQJxfU',
    appId: '1:408373931839:android:dc5e844515296554a4ed8a',
    messagingSenderId: '408373931839',
    projectId: 'radio-9ec61',
    databaseURL: 'https://radio-9ec61-default-rtdb.firebaseio.com',
    storageBucket: 'radio-9ec61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHha8ztnoV7E0v8-CCkA02xyDBK94UECU',
    appId: '1:408373931839:ios:900b1309a51d705ba4ed8a',
    messagingSenderId: '408373931839',
    projectId: 'radio-9ec61',
    databaseURL: 'https://radio-9ec61-default-rtdb.firebaseio.com',
    storageBucket: 'radio-9ec61.appspot.com',
    iosClientId: '408373931839-8884q1mi6iq8s1vfh5f2njn0ri9gbl1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.radioproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHha8ztnoV7E0v8-CCkA02xyDBK94UECU',
    appId: '1:408373931839:ios:900b1309a51d705ba4ed8a',
    messagingSenderId: '408373931839',
    projectId: 'radio-9ec61',
    databaseURL: 'https://radio-9ec61-default-rtdb.firebaseio.com',
    storageBucket: 'radio-9ec61.appspot.com',
    iosClientId: '408373931839-8884q1mi6iq8s1vfh5f2njn0ri9gbl1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.radioproject',
  );
}
